add removal info in faq + city
c3wien/Poke-That-Gmeind pull request #29
Opened 2022-05-12 13:22 UTC by pascoda

intended to resolve #8 (not tested tho)

2022-05-13 14:01 UTC, eest9 commented
Mir gefällt das direkte `<a href="mailto:wirhabenschon@luftfilterbegehren.at`… in https://github.com/c3wien/Poke-That-Gmeind/pull/29/commits/cc0ff83774d3f1b468d4a8890a0d42cf894ddb3e sowie https://github.com/c3wien/Poke-That-Gmeind/pull/29/commits/761b7fc7d8d78e326dfdcdcb9e96e38221429266 nicht, da das Spambots direkt dazu einlädt uns zuzumüllen und den Arbeitsaufwand stark erhöht sinnvolle mails raus zu filtern. @cambid eine Idee wie das besser umsetzbar ist? Ich seh oft eine Einbindung als bild, aber das ist nicht wirklich accessable.

Aber begenerell passt der Pull Request.

2022-05-14 04:40 UTC, cambid commented
>  @cambid eine Idee wie das besser umsetzbar ist? Ich seh oft eine Einbindung als bild, aber das ist nicht wirklich accessable.
Syntax mit (at) oder eine JS-Encryption, aber die ist auch nichjt zugänglich. Wir haben an div. Stellen E-Mail-Adressen direkt im HTML und ich würde das eher getrennt lösen wollen.

2022-05-14 04:45 UTC, cambid requested changes

2022-05-14 04:45 UTC, cambid commented on luftfilterbegehren/templates/general/faq.html
> +                        Erstmal: Cool, dass ihr Luftfilter installiert bzw. Pläne dazu habt. Um Um euch aus unserer Datenbank auszutragen, reicht ein formloses Email an wirhabenschon[at]luftfilterbeg
@pascoda: Folgendes ist mir noch aufgefallen:
- Das "Um" ist doppelt
- Da ist ein Blank vor dem Punkt nach der E-Mail-Adresse
- Email bitte durch E-Mail ersetzen

2022-05-14 04:45 UTC, cambid commented on luftfilterbegehren/templates/act/city.html
> +            <p class="center small indent">Falls diese Gemeinde bereits Luftfilter installiert bzw. Pläne dazu hat, entfernen wir den Eintrag gern aus unserer Datenbank. Dazu reicht ein formloses E-M
Die Leerzeichen im Betreff des mailto-Links müssen als %20 angegeben werden, da es sich hierbei um eine URL handelt.

2022-05-19 16:26 UTC, merged

2022-05-19 16:27 UTC, pascoda commented
changes requested by cambid have been incorporated; e-mail link has been changed to "wirhabenschon [at] luftfilterbegehren.at".